#!/usr/bin/env python

from scapy.all import *

for item  in range(1,256):
	ip="192.168.1."+str(item)
	pkt=Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst=ip, hwdst="ff:ff:ff:ff:ff:ff")
	response=srp1(pkt,timeout=2,verbose=0)
	if response:
		print "IP:"+response.psrc + "MAC : "+response.hwsrc
